import { Inter } from "next/font/google";
import "./globals.css";
import NavbarDesktop from "./components/Nav-desktop";
import NavBarMobile from "./components/Nav-mobile";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Underfloor heating",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="lg:block md:hidden sm:hidden">
          <NavbarDesktop />
        </div>
        <div>
          <NavBarMobile />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
